apiVersion: v1
kind: ReplicationController
metadata:
  name: speech-to-text
spec:
  replicas: 1
  selector:
    app: speech-to-text
  template:
    metadata:
      name: speech-to-text
      labels:
        app: speech-to-text
    spec:
      containers:
      - name: speech-to-text
        image: sakshi19/speech-to-text:latest
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_JSON
          valueFrom:
           secretKeyRef:
            name: binding-${service_name}
            key: binding

---

kind: Service
apiVersion: v1
metadata:
  name: speech-to-text
spec:
  selector:
    app: speech-to-text
  ports:
   - protocol: TCP
     port: 3000
    
